volumes:
  influxdb2-data:
  influxdb2-config:
  grafana_storage: 

services:
  influxdb2:
    image: influxdb:2.7.10-alpine
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    env_file:
      # relative path of env variables
      - ./config/influxdb.env 
  grafana:
    image: grafana/grafana:9.0.4
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
    env_file:
      # relative path of env variables
      - ./config/grafana.env  
    depends_on:
      influxdb2:
        condition: service_started
  monitor:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    env_file:
      # relative path of env variables
      - ./config/influxdb.env   
      - ./config/monitor.env   


